//-----------------------------------------------
// Module: system_monitor.v
//  Space Cubics OBC FPGA System Register
//-----------------------------------------------
// Copyright © 2022 Space Cubics, LLC.
//-----------------------------------------------

module system_monitor # (
  `include "sc_sysmon_bhm_init_param.vh"
) (
  // System Interface
  input HCLK,
  input HRESETN,
  input POR_RSTB,
  input REF_CLK,
  input SYS_RSTB_SYNC_REFCLK,
  output SYSMON_HW_INT,
  output SYSMON_BHM_INT,

  // AHB Interface
  input HSEL,
  input [31:0] HADDR,
  input [1:0] HTRANS,
  input [2:0] HSIZE,
  input [2:0] HBURST,
  input HWRITE,
  input HREADYIN,
  output HREADYOUT,
  input [31:0] HWDATA,
  output [31:0] HRDATA,
  output [1:0] HRESP,

  output FPGA_WATCHDOG,
  output WDOG_RST_REQ,

  // Board Health Monitor
  input CVM_DATA_REQ_TRG,
  input TEMP_DATA_REQ_TRG,
  input CVM_CRITICAL_B,
  input CVM_WARNING_B,
  input TEMP_ALERT_B,
  inout INTERNAL_I2C_SCL,
  inout INTERNAL_I2C_SDA,

  // Clock Monitor Interface
  input [1:0] OSC_CLKEN,
  input SYS_CLK,
  input MAXI_CLK,
  input ULPI_REFCLK,
  input USER_CLK1,
  input USER_CLK2,
  input CMC_REQ,
  input [1:0] CLKMODE,
  input PLLLOCK
);

wire [31:0] REG_WADR;
wire [3:0] REG_WENB;
wire [31:0] REG_WDAT;
wire REG_WWAT;
wire [31:0] REG_RADR;
wire REG_RENB;
wire [31:0] REG_RDAT;
wire REG_RWAT;
wire [6:0] XADC_DADDR;
wire XADC_DEN;
wire XADC_DWE;
wire XADC_DRDY;
wire [15:0] XADC_DI;
wire [15:0] XADC_DO;
wire [7:0] XADC_ALARM;
wire XADC_OVER_TEMP;
wire BHM_INIT_REQ;
wire [4:0] BHM_INIT_EN;
wire [4:0] BHM_MONI_EN;
wire [4:0] BHM_MONI_EN_OFF;
wire BHM_TEMP_ALERT;
wire BHM_CVM_WARN;
wire BHM_CVM_CRIT;
wire [5:0] BHM_I2C_ERR;
wire BHM_SW_ACC_END;
wire BHM_INIT_ACC_END;
wire [11:0] BHM_CVM_UPD;
wire [16*12-1:0] BHM_CVM_DAT;
wire [2:0] BHM_TEMP_UPD;
wire [16*3-1:0] BHM_TEMP_DAT;
wire BHM_SW_REQ;
wire [2:0] BHM_SW_DEVSEL;
wire [7:0] BHM_SW_DEVADR;
wire BHM_SW_RWSEL;
wire [15:0] BHM_SW_WRDATA;
wire [15:0] BHM_SW_RDDATA;
wire [15:0] BHM_CLKPSC;
wire [7:0] BHM_I2CACC_CNT;
wire [5:0] BHM_BUSY;

wire [4:0] SEM_CURRENT_STATUS;
wire [4:0] SEM_PREVIOUS_STATUS;
wire SEM_STATUS_CHANGE;
wire [7:0] HEARTBEAT_TIMEOUT;
wire HEARTBEAT_TIMEOUT_DETECT;
wire HALTED_DETECT;
wire UNCORRECT_DETECT;
wire ECORRECT_DETECT;
wire INJECT_REQ;
wire INJECT_ACK;
wire [39:0] INJECT_ADDRESS;

wire sys_clk_state;
wire sys_clk_stop;
wire maxi_clk_state;
wire maxi_clk_stop;
wire ulpi_refclk_state;
wire ulpi_refclk_stop;
wire user_clk1_state;
wire user_clk1_stop;
wire user_clk2_state;
wire user_clk2_stop;

sc_ahbip_slave # (
  .CYCLE_MODE(1)
) ahb_slave (
  // AHB Interface
  .HCLK(HCLK),
  .HRESETN(HRESETN),
  .HSEL(HSEL),
  .HADDR(HADDR),
  .HTRANS(HTRANS),
  .HSIZE(HSIZE),
  .HBURST(HBURST),
  .HWRITE(HWRITE),
  .HREADYIN(HREADYIN),
  .HREADYOUT(HREADYOUT),
  .HWDATA(HWDATA),
  .HRDATA(HRDATA),
  .HRESP(HRESP),

  // Register Interface
  .REG_WADR(REG_WADR),
  .REG_WTYP(/*open*/),
  .REG_WENB(REG_WENB),
  .REG_WDAT(REG_WDAT),
  .REG_WWAT(REG_WWAT),
  .REG_WERR(1'b0),

  .REG_RADR(REG_RADR),
  .REG_RTYP(/*open*/),
  .REG_RENB(REG_RENB),
  .REG_RDAT(REG_RDAT),
  .REG_RWAT(REG_RWAT),
  .REG_RERR(1'b0)
);

sysmon_reg # (
  .INIT_I2CPSC(SC_SYSMON_BHM_INIT_I2CPSC)
) sysmon_reg (
  .HCLK(HCLK),
  .HRESETN(HRESETN),
  .POR_RSTB(POR_RSTB),
  .REF_CLK(REF_CLK),
  .SYS_RSTB_SYNC_REFCLK(SYS_RSTB_SYNC_REFCLK),
  .SYSMON_HW_INT(SYSMON_HW_INT),
  .SYSMON_BHM_INT(SYSMON_BHM_INT),

  // Register Interface
  .REG_WADR(REG_WADR),
  .REG_WENB(REG_WENB),
  .REG_WDAT(REG_WDAT),
  .REG_WWAT(REG_WWAT),

  .REG_RADR(REG_RADR),
  .REG_RENB(REG_RENB),
  .REG_RDAT(REG_RDAT),
  .REG_RWAT(REG_RWAT),

  .FPGA_WATCHDOG(FPGA_WATCHDOG),
  .WDOG_RST_REQ(WDOG_RST_REQ),

  .XADC_DADDR(XADC_DADDR),
  .XADC_DEN(XADC_DEN),
  .XADC_DWE(XADC_DWE),
  .XADC_DRDY(XADC_DRDY),
  .XADC_DI(XADC_DI),
  .XADC_DO(XADC_DO),

  .SEM_CURRENT_STATUS(SEM_CURRENT_STATUS),
  .SEM_PREVIOUS_STATUS(SEM_PREVIOUS_STATUS),
  .SEM_STATUS_CHANGE(SEM_STATUS_CHANGE),
  .HEARTBEAT_TIMEOUT(HEARTBEAT_TIMEOUT),
  .HEARTBEAT_TIMEOUT_DETECT(HEARTBEAT_TIMEOUT_DETECT),
  .HALTED_DETECT(HALTED_DETECT),
  .UNCORRECT_DETECT(UNCORRECT_DETECT),
  .ECORRECT_DETECT(ECORRECT_DETECT),
  .INJECT_REQ(INJECT_REQ),
  .INJECT_ACK(INJECT_ACK),
  .INJECT_ADDRESS(INJECT_ADDRESS),

  .BHM_INIT_REQ(BHM_INIT_REQ),
  .BHM_INIT_EN(BHM_INIT_EN),
  .BHM_MONI_EN(BHM_MONI_EN),
  .BHM_MONI_EN_OFF(BHM_MONI_EN_OFF),
  .BHM_TEMP_ALERT(BHM_TEMP_ALERT),
  .BHM_CVM_WARN(BHM_CVM_WARN),
  .BHM_CVM_CRIT(BHM_CVM_CRIT),
  .BHM_I2C_ERR(BHM_I2C_ERR),
  .BHM_SW_ACC_END(BHM_SW_ACC_END),
  .BHM_INIT_ACC_END(BHM_INIT_ACC_END),
  .BHM_CVM_UPD(BHM_CVM_UPD),
  .BHM_CVM_DAT(BHM_CVM_DAT),
  .BHM_TEMP_UPD(BHM_TEMP_UPD),
  .BHM_TEMP_DAT(BHM_TEMP_DAT),
  .BHM_SW_REQ(BHM_SW_REQ),
  .BHM_SW_DEVSEL(BHM_SW_DEVSEL),
  .BHM_SW_DEVADR(BHM_SW_DEVADR),
  .BHM_SW_RWSEL(BHM_SW_RWSEL),
  .BHM_SW_WRDATA(BHM_SW_WRDATA),
  .BHM_SW_RDDATA(BHM_SW_RDDATA),
  .BHM_CLKPSC(BHM_CLKPSC),
  .BHM_I2CACC_CNT(BHM_I2CACC_CNT),
  .BHM_BUSY(BHM_BUSY),

  // Clock Monitor Interface
  .OSC_CLKEN(OSC_CLKEN),
  .SYS_CLK_STATE(sys_clk_state),
  .SYS_CLK_STOP(sys_clk_stop),
  .MAXI_CLK_STATE(maxi_clk_state),
  .MAXI_CLK_STOP(maxi_clk_stop),
  .ULPI_REFCLK_STATE(ulpi_refclk_state),
  .ULPI_REFCLK_STOP(ulpi_refclk_stop),
  .USER_CLK1_STATE(user_clk1_state),
  .USER_CLK1_STOP(user_clk1_stop),
  .USER_CLK2_STATE(user_clk2_state),
  .USER_CLK2_STOP(user_clk2_stop),
  .CMC_REQ(CMC_REQ),
  .CLKMODE(CLKMODE),
  .PLLLOCK(PLLLOCK)
);

xadc_ctrl xadc_ctrl (
  .REF_CLK(REF_CLK),
  .SYS_RSTB_SYNC_REFCLK(SYS_RSTB_SYNC_REFCLK),
  .HCLK(HCLK),
  .HRESETN(HRESETN),
  .XADC_DADDR(XADC_DADDR),
  .XADC_DEN(XADC_DEN),
  .XADC_DWE(XADC_DWE),
  .XADC_DRDY(XADC_DRDY),
  .XADC_DI(XADC_DI),
  .XADC_DO(XADC_DO),
  .XADC_ALARM(XADC_ALARM),
  .XADC_OVER_TEMP(XADC_OVER_TEMP)
);

sem_controller sem_controller (
  .CLK(REF_CLK),
  .RSTB(SYS_RSTB_SYNC_REFCLK),
  .SEM_CURRENT_STATUS(SEM_CURRENT_STATUS),
  .SEM_PREVIOUS_STATUS(SEM_PREVIOUS_STATUS),
  .SEM_STATUS_CHANGE(SEM_STATUS_CHANGE),
  .HEARTBEAT_TIMEOUT(HEARTBEAT_TIMEOUT),
  .HEARTBEAT_TIMEOUT_DETECT(HEARTBEAT_TIMEOUT_DETECT),
  .HALTED_DETECT(HALTED_DETECT),
  .UNCORRECT_DETECT(UNCORRECT_DETECT),
  .ECORRECT_DETECT(ECORRECT_DETECT),
  .INJECT_REQ(INJECT_REQ),
  .INJECT_ACK(INJECT_ACK),
  .INJECT_ADDRESS(INJECT_ADDRESS)
);

sysmon_bhm # (
  .SC_SYSMON_BHM_INITSET_NUM(SC_SYSMON_BHM_INITSET_NUM),
  .SC_SYSMON_BHM_INITSET_VAL(SC_SYSMON_BHM_INITSET_VAL)
) sysmon_bhm (
  // System Interface
  .HCLK(HCLK),
  .HRESETN(HRESETN),

  // Register Interface
  .BHM_INIT_REQ(BHM_INIT_REQ),
  .BHM_INIT_EN(BHM_INIT_EN),
  .BHM_MONI_EN(BHM_MONI_EN),
  .BHM_MONI_EN_OFF(BHM_MONI_EN_OFF),
  .BHM_TEMP_ALERT(BHM_TEMP_ALERT),
  .BHM_CVM_WARN(BHM_CVM_WARN),
  .BHM_CVM_CRIT(BHM_CVM_CRIT),
  .BHM_I2C_ERR(BHM_I2C_ERR),
  .BHM_SW_ACC_END(BHM_SW_ACC_END),
  .BHM_INIT_ACC_END(BHM_INIT_ACC_END),
  .BHM_CVM_UPD(BHM_CVM_UPD),
  .BHM_CVM_DAT(BHM_CVM_DAT),
  .BHM_TEMP_UPD(BHM_TEMP_UPD),
  .BHM_TEMP_DAT(BHM_TEMP_DAT),
  .BHM_SW_REQ(BHM_SW_REQ),
  .BHM_SW_DEVSEL(BHM_SW_DEVSEL),
  .BHM_SW_DEVADR(BHM_SW_DEVADR),
  .BHM_SW_RWSEL(BHM_SW_RWSEL),
  .BHM_SW_WRDATA(BHM_SW_WRDATA),
  .BHM_SW_RDDATA(BHM_SW_RDDATA),
  .BHM_CLKPSC(BHM_CLKPSC),
  .BHM_I2CACC_CNT(BHM_I2CACC_CNT),
  .BHM_BUSY(BHM_BUSY),

  // Hardware Scheduler Interface
  .CVM_DATA_REQ_TRG(CVM_DATA_REQ_TRG),
  .TEMP_DATA_REQ_TRG(TEMP_DATA_REQ_TRG),

  // Device Interface
  .CVM_CRITICAL_B(CVM_CRITICAL_B),
  .CVM_WARNING_B(CVM_WARNING_B),
  .TEMP_ALERT_B(TEMP_ALERT_B),

  // I2C Interface
  .INTERNAL_I2C_SCL(INTERNAL_I2C_SCL),
  .INTERNAL_I2C_SDA(INTERNAL_I2C_SDA)
);

sysmon_clk_checker sysmon_clk_checker (
  // Bus clock
  .HCLK(HCLK),
  .HRESETN(HRESETN),

  // Target clock
  .SYS_CLK(SYS_CLK),
  .MAXI_CLK(MAXI_CLK),
  .ULPI_REFCLK(ULPI_REFCLK),
  .USER_CLK1(USER_CLK1),
  .USER_CLK2(USER_CLK2),

  // Register Interface
  .SYS_CLK_STATE(sys_clk_state),
  .SYS_CLK_STOP(sys_clk_stop),
  .MAXI_CLK_STATE(maxi_clk_state),
  .MAXI_CLK_STOP(maxi_clk_stop),
  .ULPI_REFCLK_STATE(ulpi_refclk_state),
  .ULPI_REFCLK_STOP(ulpi_refclk_stop),
  .USER_CLK1_STATE(user_clk1_state),
  .USER_CLK1_STOP(user_clk1_stop),
  .USER_CLK2_STATE(user_clk2_state),
  .USER_CLK2_STOP(user_clk2_stop)
);

endmodule
